# Generated by Django 3.1.6 on 2021-03-25 09:00

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to=posts.models.upload_location),
        ),
    ]
